###########################################################################
#                       Lanceur de rayons simplifie                       #
###########################################################################
# ENSERB, 3me annee Informatique                               1995-1996  #
# Option AAMP, Module MP2                                                 #
#                                                                         #
###########################################################################
# Author : Gilles Subrenat                                                #
# Date   : 15 janvier 1996                                                #
#                                                                         #
# $Id$
###########################################################################/

# make -p pour avoir les macro et les regles definies 
#         dans /usr/share/lib/make/make.rules
# make -P donne les dependances des differentes cibles


# repertoire d'installation
BIN_DIR = ../bin

# mode sans test unitaire
#DEBUG = -DNDEBUG

# macro definissant ou se trouve la commande zcat
ZCAT = -DZCAT_COMMAND=\"`which zcat`\"

# Macros predefinies
CC = gcc

# options de compilation
CPPFLAGS = -I../include -I. $(DEBUG) $(ZCAT)
#CFLAGS = -O -Wall
CFLAGS = -g -Wall
LDLIBS = -lm

# application : fichier executable
BIN = lanceur


#pour changer de type de binder, mettre le bon .c
#SRC_BINDER = bnd.basic.c
SRC_BINDER = bnd.voxel.c

SRC_ALL_BINDER = bnd.basic.c  bnd.voxel.c 

HDR_BINDER = bnd.h


#pour changer de type de camera, mettre le bon .c
SRC_CAMERA = cmr.basic.c

SRC_ALL_CAMERA = cmr.basic.c

HDR_CAMERA = cmr.h


#pour changer de type de lancer de rayons, mettre le bon .c
SRC_IMAGE = img.basic.c

SRC_ALL_IMAGE = img.basic.c

HDR_IMAGE = $(SRC_IMAGE:.c=.h)


#pour changer de type de calcul d'illumination, mettre le bon .c
SRC_SCENE = scn.image.c

SRC_ALL_SCENE = scn.image.c

HDR_SCENE = $(SRC_SCENE:.c=.h)


#tous les types geometrique
SRC_GEO = geo.c geo.nappe.c geo.point.c geo.quadric.c

HDR_GEO = $(SRC_GEO:.c=.h)


#entites
SRC_ETT = ett.c

HDR_ETT = $(SRC_ETT:.c==.h)


#gestion des classes
SRC_CLASS = class.c

HDR_CLASS = $(SRC_CLASS:.c=.h)


# sources du repertoire
SRC_ALL = $(BIN:=.c) $(SRC_ALL_BINDER) $(SRC_ALL_CAMERA) $(SRC_ALL_IMAGE) $(SRC_SCENE) $(SRC_GEO) $(SRC_ETT) $(SRC_CLASS) getarg.c read_file.c

# sources pour fabriquer l'executable
SRC = $(BIN:=.c) $(SRC_BINDER) $(SRC_CAMERA) $(SRC_IMAGE) $(SRC_SCENE) $(SRC_GEO) $(SRC_ETT) $(SRC_CLASS) getarg.c read_file.c

# fichier objet cree
OBJ = $(SRC:.c=.o)

# cibles standards
all: $(BIN)

#
clean:
	$(RM) $(OBJ)

realclean: clean
	$(RM) $(BIN)

install: all
	cp $(BIN) $(BIN_DIR)

uninstall:
	cd $(BIN_DIR) ;	$(RM) $(BIN)

depend:
	makedepend -- $(CPPFLAGS) -- $(SRC_ALL)


$(BIN): $(OBJ) 
	$(CC) $(LDFLAGS) $(OBJ) $(LDLIBS) -o $@

.c.o :
	$(CC) $(CPPFLAGS) $(CFLAGS)  -c $<

#$(OBJ): $(HDR)
#	$(CC) $(CPPFLAGS) $(CFLAGS) $*.c -c
# DO NOT DELETE THIS LINE -- make depend depends on it.

